# cloudbuild.yaml
#
# Docker イメージをビルドして gcr.io に push し、Cloud Run(classnote-api) にデプロイする。
# 値を変えたい場合は --substitutions で上書き可能。

substitutions:
  _SERVICE_NAME: "classnote-api"
  _REGION: "asia-northeast1"
  _AUDIO_BUCKET: "classnote-x-audio"
  _VERTEX_REGION: "asia-northeast1"
  _GEMINI_MODEL_NAME: "gemini-2.0-flash-exp"
  _SIGNED_URL_EXPIRATION_SECONDS: "900"
  _SERVICE_ACCOUNT: "classnote-api-sa@classnote-x-dev.iam.gserviceaccount.com"

steps:
  # 1) Docker ビルド
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME", "."]

  # 2) Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_SERVICE_NAME"]

  # 3) Cloud Run デプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "$_SERVICE_ACCOUNT"
      - "--set-env-vars"
      - "GCP_PROJECT=$PROJECT_ID,AUDIO_BUCKET=$_AUDIO_BUCKET,SPEECH_RECOGNIZER_ID=projects/$PROJECT_ID/locations/asia-northeast1/recognizers/default,VERTEX_REGION=$_VERTEX_REGION,GEMINI_MODEL_NAME=$_GEMINI_MODEL_NAME,SIGNED_URL_EXPIRATION_SECONDS=$_SIGNED_URL_EXPIRATION_SECONDS"

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"

timeout: "1200s"
